spring.application.name=generative
spring.ai.ollama.base-url=http://127.0.0.1:11434
#http://localhost:11434
spring.ai.ollama.chat.options.model=gemma4:e4b
#gemma4
# Optional: Set high-concurrency for Java 21 Virtual Threads
spring.threads.virtual.enabled=true

#nginx base - /opt/homebrew/etc/nginx, 